default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: apoiar_system
  password: wilneson
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>

development:
  <<: *default
  database: apoiar_system_development

test:
  <<: *default
  database: apoiar_system_test

production:
  <<: *default
  database: apoiar_system_production
  username: apoiar_system
  # Utilize a linha abaixo para produção com variável de ambiente ou comente para utilizar a senha fixa
  # password: <%= ENV.fetch("APOIAR_SYSTEM_DATABASE_PASSWORD", "wilneson") %>
  password: wilneson

test:
 test:
  <<: *default
  database: apoiar_system_test
